CREATE TABLE IF NOT EXISTS `assetRecord`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `adminId` INT NOT NULL,
    `registrationNumber` VARCHAR(16) NOT NULL,
    `registrationDate` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `source` VARCHAR(32) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    FOREIGN KEY(`adminId`) REFERENCES user(`id`)
);