CREATE TABLE IF NOT EXISTS `borrow`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `adminId` INT NOT NULL,
    `memberId` INT NOT NULL,
    `bookId` INT NOT NULL,
    `fineStatus` BOOLEAN NOT NULL DEFAULT FALSE,
    `dateOfBorrow` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateOfReturn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateOfPayment` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    FOREIGN KEY(`adminId`) REFERENCES user(`id`),
    FOREIGN KEY(`memberId`) REFERENCES user(`id`),
    FOREIGN KEY(`bookId`) REFERENCES book(`id`)
);