CREATE TABLE IF NOT EXISTS`user`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(24) NOT NULL,
    `password` VARCHAR(32) NOT NULL,
    `lasLogin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
);